version: "2"
networks:

  default:
    driver: bridge
    
services:
  app:
    build: .
    #image: tobecrazy/ubuntu-young:latest
    container_name: tomcat
    ports:
     - "8080:8080"
    networks:
     - default
    volumes:
     - ./export/ROOT:/opt/tomcat8/webapps/ROOT
    mem_limit: 2G
