version: "2"
networks:

  default:
    driver: bridge
    
services:
  ubuntu:
    image: tobecrazy/ubuntu-young:latest
    container_name: ubuntu
    ports:
      - "8080:8800"
    networks:
    - default
    volumes:
     - ./export:/opt/tomcat8
    mem_limit: 2G
