version: "2"
networks:

  default:
    driver: bridge
    
services:
  ubuntu:
    image: tobecrazy/ubuntu-young:latest
    container_name: ubuntu
    ports:
      - "3306:3306"
    networks:
    - default
    volumes:
     - ./export:/root/export
    mem_limit: 2G
